"""initial schema

Revision ID: 38db02e12fdb
Revises: 
Create Date: 2025-07-09 16:17:56.639010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38db02e12fdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscription')
    with op.batch_alter_table('home_content', schema=None) as batch_op:
        batch_op.alter_column('subtitulo',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('imagen',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('resena', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('twofactor_code', sa.String(length=6), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('twofactor_code')
        batch_op.drop_column('resena')
        batch_op.drop_column('created')

    with op.batch_alter_table('home_content', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('subtitulo',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    op.create_table('inscription',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), nullable=True),
    sa.Column('curso', sa.VARCHAR(length=120), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('fecha', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
